apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-nginxs
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite-nginxs
  template:
    metadata:
      labels:
        app: mysite-nginxs
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html 
      volumes:
      - name: html-volume
        configMap:
          name: mysite-htmls
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-nginxs-service
spec:
  selector:
    app: mysite-nginxs
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysite-nginxs-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /app2.com
        pathType: Prefix
        backend:
          service:
            name: mysite-nginxs-service
            port:
              number: 80
