Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"




  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
    vb.name = "amya"
  end

   config.vm.network "private_network", ip: "192.168.42.110"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.hostname = "amyaS"
end

